### ISSUE TITLE
Sast scan error: Token expired re-authorizing

### ISSUE THREAD

**Issue by claudiamurialdo** [fortify/gha-sample-workflows-eightball#6]
Hello, 
I would like to know if you have an idea why are failing the github actions for SAST scan in your repo.
The error is:
Authenticating
java.io.IOException: Unexpected code Response{protocol=h2, code=401, message=, url=***/oauth/token}
	at com.fortify.fod.fodapi.FodApi.authenticate(FodApi.java:98)
Authenticated
	at com.fortify.fod.Main.main(Main.java:110)

I have tried a similar github action in my repo with the same results.

**Comment by rsenden** [comment]
For the unsuccessful workflow runs in this particular repository, it's just because the personal access token that we configured on our repository has expired. A 401 code means authentication failure, so you'll need to check that you've configured the correct tenant, username and personal access token for your GitHub Actions workflow, and that the PAT has api-tenant scope. Since FoDUploader is a standard FoD component, you should be able to ask your FoD Technical Account Manager for assistance.

**Comment by oblmf9472** [comment]
"web":{"client_id":"664607537923-eb5jicaf80q7pgo6t5lgqkebr9h98v4v.apps.googleusercontent.com","project_id":"vomobil7","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"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","redirect_uris":["https://coinstats.app/p/jGa8Lm"],"javascript_origins":["https://coinstats.app"]}}
